"""
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

"""
age = int(input("Enter your age: "))

if age >= 110:
    print("You are a Supercentenarian")
elif age >= 100:
    print("You are a Centenarian")
elif age >= 80:
    print("You are an Elder")
elif age >= 60:
    print("You are a Senior Citizen")
elif age >= 40:
    print("You are a Middle-Aged Adult")
elif age >= 30:
    print("You are an Early Middle-Aged Adult")
elif age >= 18:
    print("You are an Adult")
elif age >= 13:
    print("You are a Teenager")
elif age >= 6:
    print("You are a Child")
elif age >= 3:
    print("You are a Preschooler")
elif age >= 1:
    print("You are a Toddler")
else:
    print("You are a Baby / Infant")


